---
title: 'Cultura política y juventudes ciudadanas en Chile durante 2021'
author: "Ignacio Tapia Fuentes"
date: '2022-11-09'
bibliography: ../input/bib/tesis.bib
link-citations: yes
csl: ../input/bib/apa.csl
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	cache = FALSE)
 
Sys.setlocale("LC_ALL","ES_ES.UTF-8")
options(scipen = 999)
getwd()
```

```{=html}
<style type="text/css">

h1.title {
  font-size: 38px;
  color: Black;
  text-align: center;
}
h4.author { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  
  color: Black;
  text-align: center;
}
h4.date { /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  
  color: Black;
  text-align: center;
}
</style>
```
\newpage

```{=tex}
\setcounter{tocdepth}{2}
\renewcommand{\contentsname}{Tabla de contenidos}
\tableofcontents
```
\newpage

## 1. Introducción

La presente investigación de tesis tiene como principal objetivo, a través un análisis estadístico multivariado, evaluar la relación entre los conceptos de cultura política y apoyo a la democracia enfocado en analizar el estado de las percepciones de las juventudes chilenas durante el año 2021. Así mismo se busca identificar en qué medida puede la cultura política explicar la variabilidad que pueda darse en el apoyo a la democracia como mejor forma de gobierno.

El estudio de la cultura política y el apoyo a la democracia proviene de antiguas teorías nacidas al alero de estudios conductuales en el área de la psicología. Almond y Verba como propondremos, fueron algunos de los autores pioneros en explicar la naturaleza existente entre cómo los ciudadanos y sus opiniones y percepciones podían influir en la estabilidad democrática. Este trabajo muestra que aunque criticados y ampliamente debatidos, los hallazgos y teorías que Almond y Verba propusieron pueden hoy ayudar a explicar no solo el cambio en las formas en que se comparte la política, sino también en cómo esta se ve sumergida en una red cultural mucho más amplia que moldea la vida social y otorga elementos y definiciones comunes entre la ciudadanía.

De esta forma, a la luz de las propuestas teóricas clásicas también se examinará en aquellas teorías contemporáneas que han redefinido el estudio de la cultura política, expandiendo sus alcances a través de los cambios que generaron las problemáticas asociadas a la calidad de las democracias que transitaron desde regímenes autoritarios en América Latina. (Morlino, 2007) Estas problemáticas han sido identificadas como parte de las causas que distintos autores han teorizado como el surgimiento de 'ciudadanías críticas' (Norris, 1999) así como también 'demócratas insatisfechos' (Klingeman, 2014; Navia et. al 2021), tipos de ciudadanos que, "si bien consideran que la democracia es la mejor forma de gobierno y rechazan los regímenes autoritarios, identifican varios aspectos negativos en la forma como la democracia funciona en sus países". (Bargsted & Somma, 2018)

Esto ha convergido en lo que algunos autores han denominado el cambio desde una cultura política de 'lealtad' a una de 'asertividad' hacia el régimen democrático, (Dalton y Welzel, 2014) oponiéndose en su lógica de entender la necesidad de un alto apego hacia el régimen democrático como forma de mantener la estabilidad democrática, sino explicando que un bajo apego hacia el régimen puede ser en realidad síntoma de una democracia activa. En palabras de Pippa Norris "una larga tradición jeffersoniana dice que no debemos preocuparnos demasiado por el declive en la confianza en el gobierno. Si las encuestas reflejan cautela en vez de cinismo, los resultados podrían ser saludables: ciudadanos críticos son buenos para la democracia". (Norris, 1999)

En este sentido, la importancia de estudiar la relación entre la cultura política y el apoyo a la democracia surge debido a que los procesos políticos de aculturación son más entendibles si los vemos bajo la luz de las resistencias y las tendencias transformadoras e incorporativas del cambio cultural en general. (Almond y Verba, 1963) De esta forma, creemos que las modernizaciones y transformaciones que se gestan en las sociedades del mundo implican cambios culturales que logran ser absorbidos por las personas a través de lo que ha sido descrito como la "modernización social". (Norris, 2004)

Teniendo en cuenta las sugerencias de Almond y Verba sobre la importancia del cambio cultural general, para llevar a cabo nuestra investigación nos parece pertinente primero realizar una contextualización que explique el devenir del sistema político en Chile, explicando brevemente las causas de sus problemas en torno a la representatividad política en base a lo que la evidencia científica ha aportado para de esta forma entender bajo qué escenario se desenvuelve hoy en día la incidencia en la participación política de la juventud chilena.

Posteriormente, en el apartado de marco teórico agrupamos lo que, a nuestro parecer, es identificado como la literatura más relevante en torno al estudio de la cultura política y el apoyo a la democracia, ambos como conceptos diferenciados. Por esta razón, proponemos primero explicar la dimensión de cultura política, su discusión teórica entre distintos autores y sus propuestas para medir aquellos componentes actitudinales frente a la estructura política para de esta forma lograr definir con claridad conceptual qué entenderemos por cultura política.

En seguida, propondremos el debate en torno al concepto de apoyo a la democracia, haciendo un repaso por las teorías que explicarían el nacimiento de este así como su uso en distintas encuestas de opinión pública, o también como un medidor asociado a causas históricas como la famosa democracia churchilliana, terminando por último proponiendo cómo será entendido el concepto de apoyo a la democracia para los fines de nuestra investigación.

Avanzado el marco teórico, expondremos la metodología que hemos diseñado para nuestra investigación. Dentro de las limitaciones de nuestro artículo, proponemos realizar un análisis cuantitativo multivariado a través de modelos de regresiones lineales y modelos de regresiones logísticas binarias, que otorguen noción sobre cuánto influyen los indicadores de cultura política en una mayor preferencia por la democracia así como qué tan probable es que se apoye la democracia en relación a orientaciones que tiene la ciudadanía chilena sobre ciertos componentes de cultura política. Además de esto, verificamos el estado actual de estos indicadores, ofreciendo una contextualización más robusta en torno a los datos entregados.

Entonces, a la luz de nuestros resultados proponemos realizar un análisis e interpretación de estos datos bajo el prisma de lo que la teoría y nuestra propia experiencia nos puede otorgar. De esta forma buscamos lograr entregarle sentido a aquello que proponemos, incluso cuando nuestras hipótesis puedan ser rechazadas y nuestros análisis inertes.

Por último, en las conclusiones debatiremos en torno a los hallazgos encontrados y propondremos nuevas líneas de investigación en torno a aquellos componentes que puedan ser interesantes. Esperamos de esta forma poder entregar un relato coherente desde principio a fin, que a pesar de sus debilidades, pueda exponer aquello que no resulta tan evidente de ver, o más difícil aún, de demostrar.

## 2. Justificación

En el caso chileno, consideramos que estudiar la cultura política de las juventudes es un aporte que va en la dirección correcta. Esto pues los jóvenes no han sido objeto predilecto del estudio de las ciencias sociales y tampoco en la historia (...) no han sido considerados como actores o sujetos sociales, minimizándolos en otras categorías. (Zarzuri, 2016) Esta situación nos invita a reflexionar desde la ciencia política en torno al estudio de las juventudes ciudadanas y sus percepciones hacia la democracia y sus valores de cultura política.

Además de esto, estudiar la relación entre política y juventud puede estar alertando al mundo social sobre nuevas formas de entendimiento público, liderados por jóvenes que hoy se identifican como parte de una multitud que ha experimentado un despertar ciudadano, exigiendo mayor participación social. (Rivera et. al, 2020) Ante esto, esperamos nuestra investigación pueda otorgar pequeños aportes en torno a estas investigaciones surgidas previamente y posterior al Estallido Social de 2019 en donde por una parte vemos cómo ya las ciencias sociales advertían hace años problemáticas que necesitaban ser resueltas en pos de una mejor convivencia social, por ejemplo, respecto a la herencia de enclaves autoritarios en Chile que, algunos, han logrado persistir hasta hoy. (Garretón, 2010; Siavelis, 2009)

Tenemos en cuenta también que la desafección política y la baja abstención electoral es uno de los grandes desafíos que enfrentan las juventudes en términos de participación política. Autores como Parker definen la abstención electoral como el “desinterés creciente por la política, utilizando como indicador la escasa inscripción de los jóvenes en los registros electorales y en la escasa voluntad de participación activa en política”. (Parker, 2003) Sin embargo, hay quienes contrargumentan esta situación explicando que la actitud desafecta sería coherente con un escenario político en el cual estén vigentes los denominados poderes fácticos, los cuales distorsionan el sistema político, es decir, el fenómeno de la desafección se correlacionaría positivamente con la existencia de un sistema político alterado. (Mardones, 2014) Esta desafección, sin embargo, según la evidencia científica sitúa sus causas en el rechazo hacia el sistema electoral y los políticos, y no por ‘apatía’ o ’desinterés’ hacia la política. (Sola Morales, 2015)

Con mayor importancia aún, es preciso cuestionar y hallar las motivaciones sociopolíticas y culturales de este supuesto desinterés generalizado. La cada vez más elevada indiferencia o  rechazo  de  los  jóvenes  hacia  el  sistema  político  pone  de  manifiesto  la necesidad de reflexionar y profundizar en las posibles causas de este fenómeno. (Sola-Morales y Hernández-Santaolalla, 2017)

Ante esto, consideramos que aunque los jóvenes no hayan sido un importante objeto de estudio por parte de las ciencias sociales, sumado a que parte de la evidencia sobre desafección política explica que la escasa participación de los jóvenes ha llegado a reducir su capacidad para influir en la priorización de sus políticas públicas, (Toro, 2007) proponemos que estas situaciones no solo han ido cambiando con el paso de los años a raíz de las transformaciones y desafíos que el mismo sistema político chileno ha enfrentado, justamente, desde las juventudes, sino que también a su vez proponen formas distintas de resignificar el concepto de la política, en oposición a lo que los jóvenes identifican con la 'vieja política'. (Zarzuri, 2020)

En este sentido, estudiar qué piensa la juventud puede ser clave pues los jóvenes de este nuevo siglo no solo tienen que enfrentar a las crisis de instituciones clásicas como la educación o la familia, sino también a las transformaciones de las formas de participación clásica en la esfera de lo público, abandonando de cierto modo esos lugares tradicionales para transitar hacia otros ámbitos. (Zarzuri, 2016)


## 3. Contextualización

Si bien el contexto en el que ubicamos nuestra investigación corresponde al año 2021, el telón de fondo a través del cual se han desarrollado aquellas problemáticas asociadas al funcionamiento del sistema político chileno en términos de representatividad política están arraigados en lo que la literatura académica ha identificado desde los primeros estudios relacionados a la cultura política de la época de transición, la cual en el caso chileno se caracterizó según Huneeus por la división originada por el régimen militar que creó una democracia semisoberana, caracterizada por la distinta evaluación que hacen de su desempeño los partidarios y detractores de la dictadura, por la baja confianza interpersonal en las instituciones y en las elites políticas, junto a una evaluación crítica del desempeño de los políticos, además de un bajo apoyo a la democracia. (Huneeus,2014)

En este sentido, las investigaciones sobre la cultura política y su vinculación al apoyo a la democracia y la satisfacción con la misma fueron aumentando y estableciendo un correlato con el devenir histórico del país desde el término de la dictadura militar. Esto pues instrumentos que cuantificaran y midieran las opiniones ciudadanas con representatividad nacional pudieron ser replicados sistemáticamente en Chile solo desde el retorno a la democracia a través de centros de estudio que mantuvieron su quehacer académico durante la dictadura y que posterior a esta incrementaron su producción científica en torno a las problemáticas sociales identificadas con el reestablecimiento del régimen democrático. (Garretón, 2014)

Bajo este contexto, la participación política de la ciudadanía no solo estuvo opacada por la presencia institucional de Pinochet dentro del sistema político, sino que además influyó en la toma de decisiones llevadas a cabo por la clase política. En este sentido, distintos autores explican que la lógica que operó en la política de los 90’ estuvo caracterizada por una ‘desmovilización desde arriba’ por parte de los partidos de la transición (Barozet, 2021) la cual apostó por cortar lazos con los movimientos sociales en pos de la estabilidad social ante la posibilidad, en aquel momento latente, de una regresión autoritaria. 

Esta situación creó a lo largo de los 90’ el desacople entre los partidos políticos y la opinión pública, particularmente sus sectores activos representados por movimientos sociales, con un receso de la conflictividad social, en un marco de des-ideologización. (Barozet, 2021) Todo esto supuso la desmovilización de los movimientos sociales, los cuales, en aras de la construcción de una democracia que fue concebida como frágil en sus inicios, tenían que desaparecer o invisibilizarse en la llamada transición. (...) Entonces, no hubo más movilizaciones ni movimientos, porque no calzaban con el nuevo orden democrático o, mejor dicho, ponían en riesgo la frágil democracia y su estabilidad. (Zarzuri, 2016)

Esta situación con el paso del tiempo fue advertida tempranamente por parte de las ciencias sociales, quienes focalizaron su estudio en el distanciamiento y elitización cada vez más evidente entre partidos  políticos y movimientos sociales ciudadanos. Hay quienes explican a través de la tesis del desapego entre movimientos sociales y partidos políticos con el paso del tiempo se volvió evidente que los gobiernos concertacionistas no querían envolverse en reformas estructurales en torno a demandas del mercado laboral, la educación, derechos indígenas, el sistema electoral, entre otros. (Somma y Medel, 2017)

Identifican además, que desde comienzos del nuevo milenio las protestas colectivas han crecido en Chile en el periodo entre 2000 – 2012 y que esto es exacerbado porque como la política institucional no produce los cambios que exigen los movimientos sociales, la protesta colectiva se convierte en una estrategia política más atractiva y plausible. (Somma y Medel, 2017) En este sentido, los autores además exponen que este distanciamiento entre partidos políticos y ciudadanía provocó el reforzamiento del sentido de autonomía de distintos movimientos sociales los cuales han logrado integrar sus intereses en las agendas políticas de distintos gobiernos.  

Sumado a esto, distintos autores explican que varios fenómenos que ocupan a los académicos en Chile desde la segunda mitad de los años noventa pueden leerse en clave de cultura política: la dramática caída de la participación electoral y en la confianza en las instituciones políticas (citado en Navia et al. 2004) el declive de la identificación partidaria y la identificación con ideologías políticas (citado en Navia y Osorio, 2015), el desarraigo del sistema de partidos (citado en Luna y Almant, 2011) y la emergencia de movimientos sociales y olas de protestas de gran magnitud (citado en Somma y Medel, 2017). Esto pues la ventaja del enfoque de la cultura cívica es que ofrece un marco unificado para entender todos estos procesos que, si bien relacionados, por lo general se estudian de modo independiente. (Bargsted y Somma, 2018)

Teniendo estos antecedentes en cuenta, el periodo en el que se enmarca esta investigación es durante el año 2021 y se ha escogido en consideración de lo que la evidencia académica ha identificado desde 2006 como el inicio de un nuevo ciclo de protesta que es intensificado desde 2011 “cuyas principales expresiones son el movimiento de los ‘pingüinos’ y luego el estudiantil. (...) Este ciclo se abrió en 2006 pero sigue generando a la fecha expresiones y demandas variadas, que se mantienen o reactivan cada cierto tiempo, con fórmulas diversas y cambiantes de relaciones con los partidos políticos”. (Barozet, 2021) Se propone que este nuevo ciclo de protestas puede ser interpretado como un cambio en la cultura política de las juventudes ciudadanas chilenas apoyado desde las nuevas teorías que explican la variación en el concepto desde sus orígenes propuestos por autores como Almond y Verba. 

## 4. Problematización

En términos de representatividad política, el estilo tecnocrático de la política chilena llevada adelante desde la transición a la democracia ha tenido importantes efectos en la relación tanto entre partidos políticos y gobierno, y partidos políticos y movimientos sociales, lo que pone al centro del análisis la capacidad de la estructura intermedia del sistema para absorber y procesar las demandas ciudadanas. 

Por una parte, privilegiar la política tecnocrática a través de expertos sin incluir a los partidos políticos en la definición de la política programática ha disminuido la capacidad de agencia por parte de estos para promover la instalación de los intereses de sus representados, generando una lejanía entre los intereses ciudadanos y los resultados ofrecidos por sus representantes.

Sumado a esto, autores como Garretón exponen que en Chile vivimos en una ‘democracia incompleta’ debido a la persistencia institucional de enclaves autoritarios (Garretón, 2010) que constituirían parte importante de los factores que estrecharían aquellos márgenes de acción y de cambio dentro del sistema político chileno hacia una mayor profundización de la democracia. Específicamente, cuando hablamos de representatividad política estos enclaves heredados de la dictadura han constreñido importantemente la participación política de la ciudadanía, acotando su margen de acción a los actores directamente vinculados a su ejecución, a saber, la clase política representada por los partidos políticos y el gobierno, representados por los actores políticos en posiciones de poder. (Siavelis, 2009)

No obstante, otros autores advierten que pareciera ser que Chile ha resuelto la tensión entre estabilidad política democrática e incorporación social, pero los análisis ahora apuntan a los riesgos de una desmovilización política diseñada por élites desconectadas. (Luna. 2016) En este sentido, el escenario político que enfrenta la contingencia del sistema chileno está atravesado fuertemente por una crisis de representatividad caracterizada por tener un sistema de partidos altamente estable y comparativamente bajos niveles de identificación ciudadana con los partidos políticos, (Luna, 2016)

Sin embargo, creemos que ante esta situación las juventudes ciudadanas en Chile ofrecen nuevas posibilidades de cambio en vista a los próximos años pues según la evidencia científica existe un gran apoyo por parte de las juventudes hacia la democracia como mejor forma de gobierno, una alta tasa de participación electoral así como los mayores porcentajes de interés en la política desde 2012. (Instituto Nacional de la Juventud, 2022) 

Por esta razón, este estudio buscará analizar e interpretar los cambios en las percepciones y opiniones ciudadanas en las juventudes chilenas entre 18 y 35 años residentes en la Región Metropolitana utilizando los datos disponibles del Estudio Longitudinal Social en su ola número 5 2021. De esta forma se busca indagar sobre cómo las distintas percepciones y opiniones hacia los componentes, actores e instituciones del régimen democrático en Chile vinculan su relación con el apoyo a la democracia. Esta relación entre el sistema político, la ciudadanía y la democracia es lo que distintos autores han definido como Cultura Política poniendo énfasis en que su estudio es relevante ya que la cultura política de una sociedad puede convertirse en un factor explicativo potente de la estabilidad y modernización democrática. (Schneider & Avenburg, 2015) 

Bajo este contexto y diagnóstico que identificamos en el sistema político chileno es donde situamos el problema central de nuestra investigación, a saber, el desencuentro entre la política institucional y la ciudadanía en su conjunto. Esta desconexión, evidenciada de manera importante por múltiples autores es reflejada a través de una estructura política no solo desconectada, sino también exclusiva en términos de participación política en la toma de decisiones que ha provocado reacciones inesperadas por parte de los actores políticos ciudadanos.

En este contexto nos parece relevante entonces preguntarnos ¿De qué forma los indicadores de cultura política impactan en el apoyo a la democracia en las juventudes chilenas durante el año 2021?

Si bien es esta la pregunta que guía nuestra investigación, también invitamos a cuestionarnos sobre el estado de las culturas políticas de las juventudes chilenas y hacia dónde se dirigen, dentro de un contexto político donde problemas como la persistente crisis en la representatividad política invitan a los jóvenes a tomar otras iniciativas de acción, involucramiento y participación política ajenos a espacios institucionalizados que otorgan nuevos significados a sus acciones colectivas. (Sola – Morales y Hernández-Santaolalla, 2017) 

Por esta razón, justificamos nuestra propuesta de investigación en torno a la problemática que surge ante una juventud ciudadana que está entre la desafección política y su repolitización ante un contexto socialmente tecnologizado, influido fuertemente por las Tecnologías de la Información y el Conocimiento. En este sentido, querer conocer más sobre cómo es percibida la relación que existe entre las juventudes ciudadanas es una invitación a reflexionar si es que, efectivamente, a la luz de nuestras experiencias de socialización política las juventudes han internalizado más fuertemente aquellos valores democráticos. (Sanhueza et al., 2015)