---
title: 'Cultura política y juventudes ciudadanas en Chile durante 2021'
author: "Ignacio Tapia Fuentes"
date: '2022-11-09'
bibliography: ../input/bib/tesis.bib
link-citations: yes
csl: ../input/bib/apa.csl
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	cache = FALSE)
 
Sys.setlocale("LC_ALL","ES_ES.UTF-8")
options(scipen = 999)
getwd()
```

```{=html}
<style type="text/css">

h1.title {
  font-size: 38px;
  color: Black;
  text-align: center;
}
h4.author { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  
  color: Black;
  text-align: center;
}
h4.date { /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  
  color: Black;
  text-align: center;
}
</style>
```
\newpage

```{=tex}
\setcounter{tocdepth}{2}
\renewcommand{\contentsname}{Tabla de contenidos}
\tableofcontents
```
\newpage

## 1. Introducción

La presente investigación de tesis tiene como principal objetivo, a través un análisis estadístico multivariado, evaluar la relación entre los conceptos de cultura política y apoyo a la democracia enfocado en analizar el estado de las percepciones de las juventudes chilenas. Así mismo se busca identificar si puede la cultura política explicar los cambios que puedan darse en el apoyo a la democracia como mejor forma de gobierno.

El estudio de la cultura política y el apoyo a la democracia proviene de antiguas teorías nacidas en al alero de estudios conductuales en el área de la psicología. Almond y Verba como propondremos, fueron algunos de los autores pioneros en explicar la naturaleza existente entre cómo los ciudadanos y sus opiniones y percepciones podían influir en la estabilidad democrática. Este trabajo muestra que aunque criticados y ampliamente debatidos, los hallazgos y teorías que Almond y Verba propusieron pueden hoy ayudar a explicar no solo el cambio en las formas en que se comparte la política, sino también en cómo esta se ve sumergida en una red cultural mucho más amplia que moldea la vida social y otorga elementos y definiciones comunes entre la ciudadanía. 

De esta forma, a la luz de las propuestas teóricas clásicas también se examinará en aquellas teorías contemporáneas que han redefinido el estudio de la cultura política, expandiendo sus alcances a través de los cambios que generaron hacia el desarrollo de lo que distintos autores han llamado ‘ciudadanías críticas’ (Norris, 1999) así como también ‘demócratas insatisfechos’ (Klingeman, 2014; Navia et. al 2021), tipos de ciudadanos que, “si bien consideran que la democracia es la mejor forma de gobierno y rechazan los regímenes autoritarios, identifican varios aspectos negativos en la forma como la democracia funciona en sus países”. (Bargsted & Somma, 2018. Pag 195) 

Esto ha convergido en lo que algunos autores han denominado el cambio desde una cultura política de ‘lealtad’ a una de ‘asertividad’ hacia el régimen democrático, (Dalton y Welzel, 2014) oponiéndose en su lógica de entender la necesidad un alto apego hacia el régimen democrático como forma de mantener la estabilidad democrática, sino explicando que un bajo apego hacia el régimen puede ser en realidad síntoma de una democracia activa. En palabras de Pippa Norris “una larga tradición jeffersoniana dice que no debemos preocuparnos demasiado por el declive en la confianza en el gobierno. Si las encuestas reflejan cautela en vez de cinismo, los resultados podrían ser saludables: ciudadanos críticos son buenos para la democracia”. (Norris, 1999)

En este sentido, la importancia de estudiar la relación entre la cultura política y el apoyo a la democracia surge debido a que los procesos políticos de aculturación son más entendibles si los vemos bajo la luz de las resistencias y las tendencias transformadoras e incorporativas del cambio cultural en general. (Almond y Verba, 1963) De esta forma, creemos que las modernizaciones y transformaciones que se gestan en las sociedades del mundo implican cambios culturales que logran ser absorbidos por las personas a través de lo que ha sido descrito como la “modernización social”. (Norris, 2004)

En el caso chileno, consideramos que estudiar la cultura política de las juventudes es un aporte que va en la dirección correcta. Esto pues los jóvenes no han sido objeto predilecto del estudio de las ciencias sociales y tampoco en la historia (...) no han sido considerados como actores o sujetos sociales, minimizándolos en otras categorías. (Zarzuri, 2016) Esta situación nos invita a reflexionar desde la ciencia política en torno al estudio de las juventudes ciudadanas y sus percepciones hacia la democracia y su valores de cultura política.

Además de esto, estudiar la relación entre política y juventud puede estar alertando al mundo social sobre nuevas formas de entendimiento público, liderados por jóvenes que hoy se identifican como parte de una multitud que ha experimentado un despertar ciudadano, exigiendo mayor participación social. (Rivera et. al, 2020) Ante esto, esperamos nuestra investigación pueda otorgar pequeños aportes en torno a estas investigaciones surgidas previamente y posterior al Estallido Social de 2019 en donde por una parte vemos cómo ya las ciencias sociales advertían hace años problemáticas que necesitaban ser resueltas en pos de una mejor convivencia social, por ejemplo, respecto a la herencia de enclaves autoritarios en Chile que, algunos, han logrado persistir hasta hoy. (Garretón, 2010)


No obstante, consideramos que aunque los jóvenes no hayan sido un importante objeto de estudio por parte de las ciencias sociales, sumado a que parte de la evidencia sobre desafección política explica que la escasa participación de los jóvenes ha llegado a reducir su capacidad para influir en la priorización de sus políticas públicas (Toro, 2007) estas situaciones han ido cambiando con el paso de los años a raíz de los cambios que el mismo sistema político chileno ha enfrentado, justamente, desde las juventudes. En este sentido, estudiar qué piensa la juventud puede ser clave para imaginar el devenir de nuestra sociedad.

Teniendo en cuenta las sugerencias de Almond y Verba sobre la importancia del cambio cultural general, para llevar a cabo nuestra investigación nos parece pertinente primero realizar una contextualización que explique el devenir del sistema político en Chile, explicando brevemente las causas de sus problemas en torno a la representatividad política en base a lo que la evidencia científica ha aportado para de esta forma entender bajo qué escenario se desenvuelve hoy en día la incidencia de la juventud chilena. 

Posteriormente, en el apartado de marco teórico hemos reunido lo que hemos identificado como la literatura más relevante en torno al estudio de la cultura política y el apoyo a la democracia, ambos como conceptos diferenciados. Por esta razón, proponemos primero explicar la dimensión de cultura política, su discusión teórica entre distintos autores y sus propuestas para medir aquellos componentes actitudinales frente a la estructura política para de esta forma lograr definir con claridad conceptual qué entenderemos por cultura política. 

En seguida, propondremos el debate en torno al concepto de apoyo a la democracia, haciendo un repaso por las teorías que explicarían el nacimiento de este así como su uso en distintas encuestas de opinión pública, o también como un medidor asociado a causas históricas como la famosa democracia churchilliana, terminando por último proponiendo cómo será entendido el concepto de apoyo a la democracia para los fines de nuestra investigación.

Avanzado el marco teórico, expondremos la metodología que hemos diseñado para nuestra investigación. Dentro de las limitaciones de nuestra investigación, proponemos realizar un análisis cuantitativo a través de modelos de regresiones lineales y modelos de regresiones logísticas binarias, que otorguen noción sobre cuánto influyen los indicadores de cultura política en una mayor preferencia por la democracia así como qué tan probable es que se apoye la democracia en relación a orientaciones que tiene la ciudadanía chilena sobre ciertos componentes de cultura política. Además de esto, verificamos el estado actual de estos indicadores, ofreciendo una contextualización más robusta en torno a los datos entregados. 

Entonces, a la luz de nuestros resultados proponemos realizar un análisis e interpretación de estos datos bajo el prisma de lo que la teoría y nuestra propia experiencia nos puede otorgar. De esta forma buscamos lograr entregarle sentido a aquello que proponemos, incluso cuando nuestras hipótesis puedan ser rechazadas y nuestros análisis inertes. 

Por último, en las conclusiones debatiremos en torno a los hallazgos encontrados y propondremos nuevas líneas de investigación en torno a aquellos componentes que puedan ser interesantes. Esperamos de esta forma poder entregar un relato coherente desde principio a fin, que a pesar de sus debilidades, pueda exponer aquello que no resulta tan evidente de ver, o más difícil aún, de demostrar.

